# Loan Default Prediction

---

## 1. Environment Setup

In [26]:
import numpy as np
import pandas as pd
import plotly.express as px

In [27]:
data_path = "Data/Loan_Data.csv"

---

## 2. Data Exploration

In [28]:
df = pd.read_csv(data_path)
df.head()

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
0,8153374,0,5221.545193,3915.471226,78039.38546,5,605,0
1,7442532,5,1958.928726,8228.752520,26648.43525,2,572,1
2,2256073,0,3363.009259,2027.830850,65866.71246,4,602,0
3,4885975,0,4766.648001,2501.730397,74356.88347,5,612,0
4,4700614,1,1345.827718,1768.826187,23448.32631,6,631,0

In [29]:
df.shape, df.dtypes

((10000, 8),
 customer_id                   int64
 credit_lines_outstanding      int64
 loan_amt_outstanding        float64
 total_debt_outstanding      float64
 income                      float64
 years_employed                int64
 fico_score                    int64
 default                       int64
 dtype: object)

In [30]:
df.isna().sum()

customer_id                 0
credit_lines_outstanding    0
loan_amt_outstanding        0
total_debt_outstanding      0
income                      0
years_employed              0
fico_score                  0
default                     0
dtype: int64

---

## 3. Data Analysis

In [31]:
df.describe()

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.974577e+06,1.461200,4159.677034,8718.916797,70039.901401,4.552800,637.557700,0.185100
std,2.293890e+06,1.743846,1421.399078,6627.164762,20072.214143,1.566862,60.657906,0.388398
min,1.000324e+06,0.000000,46.783973,31.652732,1000.000000,0.000000,408.000000,0.000000
25%,2.977661e+06,0.000000,3154.235371,4199.836020,56539.867903,3.000000,597.000000,0.000000
50%,4.989502e+06,1.000000,4052.377228,6732.407217,70085.826330,5.000000,638.000000,0.000000
75%,6.967210e+06,2.000000,5052.898103,11272.263740,83429.166133,6.000000,679.000000,0.000000
max,8.999789e+06,5.000000,10750.677810,43688.784100,148412.180500,10.000000,850.000000,1.000000

In [32]:
df["loan_amt_outstanding_norm"] = (
    df["loan_amt_outstanding"] - df["loan_amt_outstanding"].min()
) / (df["loan_amt_outstanding"].max() - df["loan_amt_outstanding"].min())

In [33]:
df.describe().to_csv("Data/Loan_Data_Describe.csv")

In [34]:
px.histogram(df, x="default", title="Credit Default Distribution")

##### We can see a visible class imbalance

In [35]:
px.box(df, x="income", title="Income Distribution", color="default")

In [36]:
px.histogram(
    df,
    x="credit_lines_outstanding",
    color="default",
    title="Credit Lines Outstanding Distribution",
)

In [37]:
px.histogram(
    df,
    x="loan_amt_outstanding",
    color="default",
    title="Loan Amount Outstanding Distribution",
)

In [38]:
px.histogram(
    df,
    x="total_debt_outstanding",
    color="default",
    title="Total Debt Outstanding Distribution",
)

In [39]:
px.box(df, x="fico_score", color="default", title="Fico Score Distribution")

In [40]:
px.box(df, x="years_employed", color="default", title="Employment years Distribution")

In [41]:
corr_matrix=df.corr().round(2)
corr_matrix

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default,loan_amt_outstanding_norm
customer_id,1.00,0.01,-0.01,0.00,-0.01,-0.01,0.01,0.01,-0.01
credit_lines_outstanding,0.01,1.00,0.08,0.85,0.02,-0.09,-0.26,0.86,0.08
loan_amt_outstanding,-0.01,0.08,1.00,0.40,0.84,-0.16,-0.03,0.10,1.00
total_debt_outstanding,0.00,0.85,0.40,1.00,0.39,-0.17,-0.23,0.76,0.40
income,-0.01,0.02,0.84,0.39,1.00,0.00,-0.01,0.02,0.84
years_employed,-0.01,-0.09,-0.16,-0.17,0.00,1.00,0.26,-0.28,-0.16
fico_score,0.01,-0.26,-0.03,-0.23,-0.01,0.26,1.00,-0.32,-0.03
default,0.01,0.86,0.10,0.76,0.02,-0.28,-0.32,1.00,0.10
loan_amt_outstanding_norm,-0.01,0.08,1.00,0.40,0.84,-0.16,-0.03,0.10,1.00

In [42]:
import plotly.express as px
# Create heatmap with plotly
fig = px.imshow(corr_matrix,
                title="Correlation Matrix",
                labels={'color':'Correlation'},  # Label for the color bar
                color_continuous_scale='Blues',  # Set color scheme to blue
                aspect="auto",
                text_auto=True)

# Show plot
fig.show()

---

## 4. Data Processing

In [43]:
df.head()

,customer_id,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default,loan_amt_outstanding_norm
0,8153374,0,5221.545193,3915.471226,78039.38546,5,605,0,0.483447
1,7442532,5,1958.928726,8228.752520,26648.43525,2,572,1,0.178640
2,2256073,0,3363.009259,2027.830850,65866.71246,4,602,0,0.309815
3,4885975,0,4766.648001,2501.730397,74356.88347,5,612,0,0.440948
4,4700614,1,1345.827718,1768.826187,23448.32631,6,631,0,0.121362

In [44]:
df.drop(columns=["customer_id"], inplace=True)

In [45]:
df["default"] = df["default"].astype(np.bool)

In [46]:
df[df.columns.drop(["default", "credit_lines_outstanding"])] = df[
    df.columns.drop(["default", "credit_lines_outstanding"])
].apply(lambda x: (x - x.mean()) / x.std())

In [47]:
df.head()

,credit_lines_outstanding,loan_amt_outstanding,total_debt_outstanding,income,years_employed,fico_score,default,loan_amt_outstanding_norm
0,0,0.747058,-0.724812,0.398535,0.285411,-0.536743,False,0.747058
1,5,-1.548297,-0.073963,-2.161768,-1.629243,-1.080777,True,-1.548297
2,0,-0.560481,-1.009645,-0.207909,-0.352807,-0.586201,False,-0.560481
3,0,0.427024,-0.938137,0.215073,0.285411,-0.421342,False,0.427024
4,1,-1.979634,-1.048728,-2.321198,0.923629,-0.108110,False,-1.979634

In [48]:
df.to_csv("Data/datasetfinal.csv", index=False)